#!/bin/bash
# 成就徽章emoji图标更新 - Docker重启指南

echo "================================================"
echo "成就徽章emoji图标更新"
echo "================================================"

echo ""
echo "【问题说明】"
echo "后端代码已更新为emoji图标定义，但Docker容器仍在运行旧代码。"
echo "需要重启容器以加载新的Python代码。"
echo ""

echo "【解决方案】"
echo ""
echo "方法1: 使用启动脚本重启"
echo "  cd /Users/xuning/workspace/project/git/ML/openmaic-business/packages/server-python"
echo "  bash scripts/start.sh"
echo "  选择: 4 (停止服务) -> 然后再选择: 1 (开发模式)"
echo ""

echo "方法2: 直接使用docker-compose命令"
echo "  cd /Users/xuning/workspace/project/git/ML/openmaic-business"
echo "  docker-compose restart server-python"
echo "  或:"
echo "  docker-compose down"
echo "  docker-compose up -d"
echo ""

echo "方法3: 重新构建镜像（推荐）"
echo "  cd /Users/xuning/workspace/project/git/ML/openmaic-business"
echo "  docker-compose build server-python"
echo "  docker-compose up -d"
echo ""

echo "================================================"
echo "验证更新"
echo "================================================"

echo ""
echo "重启后，请刷新移动端Profile页面："
echo "  1. 拉取刷新页面"
echo "  2. 成就徽章应该显示emoji图标"
echo ""
echo "预期的emoji图标："
echo "  🔥 连续7天"
echo "  💪 连续30天"
echo "  👑 百日传奇"
echo "  📚 完成5课"
echo "  🎓 完成10课"
echo "  ✨ 笔记达人"
echo "  ⏰ 百小时"
echo "  🚀 五百小时"
echo "  🏆 测验高手"
echo ""