-- 用户扩展字段：学习兴趣、社交账号、隐私设置
ALTER TABLE users ADD COLUMN IF NOT EXISTS interests VARCHAR(500) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS wechat VARCHAR(100) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS weibo VARCHAR(100) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS github VARCHAR(100) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin VARCHAR(200) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS show_progress BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS show_social BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS allow_message BOOLEAN DEFAULT TRUE;